### ISSUE TITLE
svelte-kit issues with SSR

### ISSUE THREAD

**Issue by kilianso** [cibernox/svelte-intl-precompile#22]
Hey there! I running into some issues using Sveltekit and SSR.

### SSR issues

1. Whenever I'm starting the server with `npm run dev`, an error occurs in the terminal: 
```
[vite] Error when evaluating SSR module /node_modules/precompile-intl-runtime/dist/modules/stores/formatters.js:
SyntaxError: Unexpected token '||='
```
This even persists if I disable SSR in the svelte.config.js file. 
If SSR is disabled, the app seems to work even with that error.

2. Having SSR enabled using `addMessages` in my `__layout.svelte` file, devserver and build fails with this error in the terminal:
```
__vite_ssr_import_3__.addMessages is not a function
```

3. In your docs, you write `type="module"` but it should be `context="module"` to load it in the layout file. However, you cannot subscribe to a store value within a module context. So `$session` fails. You could only use `get` instead: https://github.com/sveltejs/svelte/issues/4306

4. The trick with the hook to split the "accept-language" string is not working if you build the app using static-adapter. There should be an additional check like: 
```
let acceptedLanguage = request.headers["accept-language"] && request.headers["accept-language"].split(',')[0];`
```

5. If I import a JSON file like `$locales/en.json` Vite fails with this: 
```
09:06:06 [vite] Internal server error: Failed to parse JSON file.
```
If I import it as a JS or TS file, it works. Even though it's a JSON file. Is this expected behavior?

### environment
MacOS: 10.15.7
Node: 14.18.0
NPM: 6.14.15
svelte-kit: 1.0.0-next.180
vite: 2.6.3

**Comment by kilianso** [comment]
Thanks for that quick response. Can confirm that issues 1 & 2 are gone when using Node 16. Would be cool if you could share your opinion on 3,4 and 5.

**Comment by cibernox** [comment]
I was AFK all day.

3. Thanks, I fixed that typo. Regarding the store, I might need more information about what you want to do. I say that you should load the library and set the locale and translations in a context module because it's what runs first, but nothing prevents you from defining a non-module script. Did you check and run the sample app in https://github.com/cibernox/sample-app-svelte-intl-precompile/ ? Maybe you can compare things and check what's different.

4. I added that check too. I don't use the static adapter myself but it's always good to not assume a header will be present.
