### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by EskelCz** [cibernox/svelte-intl-precompile#61]
Is there a way to incorporate basic HTML tags? In principle, if this is even a valid feature request or not.

Right now I have to concatenate strings to achieve basic formatting (bold, italic etc), or simply don't use the locale files for certain texts at all.

**Comment by cibernox** [comment]
Right now you can use the `{@html t('foo')}`, since the one escaping HTML tags is svelte itself, not this library. 
However I agree it's not very convenient if you have a lot of situations where this is common.

I did see that some i18n libraries use some kind of convention, like having translations keys ending in `_html` be automatically unscapped, that could make it more convenient but i haven't investigated much about how that would be possible with svelte.

**Comment by EskelCz** [comment]
`{@html t('foo')}` is just what I needed. Thanks a lot
