### ISSUE TITLE
failed to import "svelte-intl-precompile"

### ISSUE THREAD

**Issue by MarcGodard** [cibernox/svelte-intl-precompile#65]
```
11:16:24 a.m. [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "svelte-intl-precompile"
|- Error [ERR_REQUIRE_ESM]: require() of ES Module /home/marcgodard/Documents/Github/swp-web/node_modules/svelte/src/runtime/store/index.js from /home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js not supported.
Instead change the require of index.js in /home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js:5:17)
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/includes/loaderQueue.js:4:22)
    at Object.<anonymous> (/home/marcgodard/Documents/Github/swp-web/node_modules/precompile-intl-runtime/dist/commonjs/index.js:18:23)
    at async Promise.all (index 0)
    at async nodeImport (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55947:17)
    at async ssrImport (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55840:24)
    at async eval (/home/marcgodard/Documents/Github/swp-web/src/routes/+page.svelte:4:31)
    at async instantiateModule (file:///home/marcgodard/Documents/Github/swp-web/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55902:9)
```

**Comment by MarcGodard** [comment]
After updating all my packages.

**Comment by MarcGodard** [comment]
@cibernox Yeah I saw that... but this was the cause. There was also an update in the svelte plugin lib... Investigating more

**Comment by TimonStadelmann** [comment]
I have the same problem. Any workarounds yet?

**Comment by cibernox** [comment]
I'm not sure what is going on, I don't think any of the changes introduced recently could have caused this. I have verified the problem locally on a sample app. I can only guess there has been some change in vite since the last published version, but I'll track it down.

**Comment by dlebech** [comment]
While manually implementing a temporary workaround in the package-lock.json I noticed something:
- When using new version `svelte-intl-precompile` version 0.12.2, the dependecy for `precompile-intl-runtime` has its own entry like `"node_modules/precompile-intl-runtime": {...}` for version 0.8.4
- When downgrading to using version 0.12.1 and 0.8.2 (this requires hardcoding version `0.8.2` instead of `^0.8.2` in the package-lock dependencies for svelte-intl-precompile), the entry in package-lock looks like `"node_modules/svelte-intl-precompile/node_modules/precompile-intl-runtime": { ... }`

So it's like it uses two different ways of referencing `precompile-intl-runtime` library, either as a separate library or sub-folder module.

Note that `npm i -S svelte-intl-precompile@0.12.1 precompile-intl-runtime@0.8.2` *does not work*, but hardcoding the dependency value 0.8.2 does as mentioned above.

Here's the three entries that work if you make sure to remove the node_modules/precompile-intl-runtime entry as well:

**Comment by dlebech** [comment]
I wonder if you're somehow randomly running into a problem I also had with a library some months ago in a hybrid cjs/mjs setting. Your setup looks very similar.

I had to add `"exports"` to the main package.json as well as extra, minimal package.json files inside each subfolder for mjs/cjs via a "fixup" script as part of the build. It was based on this blog post: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

Here's my library package.json: https://github.com/exitplanner/xbrl-parser/blob/main/package.json

**Comment by EricRovell** [comment]
Same problem here, after updating all my packages (migrating to svelte 4) I have the same error: `Error [ERR_REQUIRE_ESM]: require() of ES Module...`

**Comment by macmillen** [comment]
I have the same problem and still can't upgrade to svelte 4 :(

**Comment by stalkerg** [comment]
yep, new version is not working:
```
Instead change the require of index.js in spa/node_modules/precompile-intl-runtime/dist/commonjs/stores/dictionary.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by stalkerg** [comment]
1. Why `precompile-intl-runtime` is CommonJS package without `"type":"module"`? At the same time, it's included ESM modules file.
2. Such files use `import` without extension which means they can work with `--experimental-specifier-resolution=node` only.

**Comment by stalkerg** [comment]
It seems like https://github.com/cibernox/precompile-intl-runtime/blob/master/tsconfig.json#L3 should be `NodeNext` to support relative import wich should include `.js` extension.

**Comment by cibernox** [comment]
That is helpful. I come from a trip tonight, I will church that

**Comment by tobiaskohlbau** [comment]
As pointed out by @stalkerg it's a bit confusing why _precompile-intl-runtime_ is provided as more aligned to commons as to ESM. _svelte-intl-precompile_ instead is configured to be a native ESM. I can only assume this was due to jest and babel complaining about issues. I've tried to move the project itself to an ESM which still supports CommonJS via _export_ definition in _package.json_ in addition to main pointing to commonjs. I've provided an PR which should resolve this issue. Please note that I'm not as common with the node/JS ecosystem, please let me know if the PR needs to be adjusted in order to align with the maintainers or other best practices.

**Comment by cibernox** [comment]
v0.12.3 has fixed this. Try the new version and report if it works on your projects.
