### ISSUE TITLE
Can't figure out how to use translation variables

### ISSUE THREAD

**Issue by MarcGodard** [cibernox/svelte-intl-precompile#7]
I tried:

```
{$t("foot", { default: 'hello', count: 1 })}
```

The default works, but using the example, the count isn't working. What am I missing?

**Comment by cibernox** [comment]
I copied the API from `svelte-i18n`. Values must be passed inside a `values` key.
In your example it should be `{$t("foot", { default: 'hello', values: { count: 1 } })}`. I personally don't like that too much, I find it a bit verbose, but since svelte-i18n is the most popular i18n library for svelte by a lot I thought it was wise to just use the exact same API to make transitioning to this library dead simple.

**Comment by cibernox** [comment]
You can find the docs for svelte-i18n here about this topic in https://github.com/kaisermann/svelte-i18n/blob/main/docs/Formatting.md#format-_-or-t

**Comment by MarcGodard** [comment]
Has this been tested with the latest kit version? Its not working for me and its the ONLY thing I added so far.

**Comment by cibernox** [comment]
Yes, it does work. I just created a test app quickly to prove it: https://github.com/cibernox/quick-i18n-throwaway-demo

**Comment by MarcGodard** [comment]
@cibernox Thanks, must be missing something.

**Comment by cibernox** [comment]
@MarcGodard if you find what you missed let me know, it's probably a signal that I should improve the readme.

**Comment by MarcGodard** [comment]
There was a svelte error that was causing all this. Once I fixed it, it fixed this.

**Comment by cibernox** [comment]
Great to hear, closing this!
